name: Install Dependencies

on:
  push:
    branches:
      - develop  

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0' 

      - name: Restore dependencies
        run: dotnet restore
