name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Debug
      - name: List directory contents
        run: ls -R ./bin/Debug/net8.0
      - name: Build Docker image
        run: |
          docker build -t qualitymonitoring_fiap:latest .  # Usando um nome de imagem local

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Staging
        run: |
          # Criando e executando o container a partir da imagem local
          docker run -d --name staging-container -p 8080:80 qualitymonitoring_fiap:latest
          az webapp config container set --name my-staging-app --resource-group FIAP --container-image-name qualitymonitoring_fiap:latest

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Production
        run: |
          # Criando e executando o container a partir da imagem local
          docker run -d --name production-container -p 8081:80 qualitymonitoring_fiap:latest
          az webapp config container set --name my-production-app --resource-group FIAP --container-image-name qualitymonitoring_fiap:latest
